apiVersion: v1
kind: ConfigMap
metadata:
  name: quoter-config
  namespace: quoter
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc.quoter.svc.cluster.local:5432/quoterdb"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-svc.quoter.svc.cluster.local:9092"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics,circuitbreakers"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRICEFEED_SLIDINGWINDOWSIZE: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRICEFEED_FAILURE_RATE_THRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_PRICEFEED_WAIT_DURATION_IN_OPEN_STATE: "30s"
  LOG_LEVEL: "INFO"
