apiVersion: v1
kind: ResourceQuota
metadata:
  name: quoter-quota
  namespace: quoter
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "6Gi"
    limits.cpu: "8"
    limits.memory: "12Gi"
    pods: "20"
    persistentvolumeclaims: "5"
