apiVersion: v1
kind: Secret
metadata:
  name: quoter-secrets
  namespace: quoter
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "quoter"
  SPRING_DATASOURCE_PASSWORD: "REDACTED_PASSWORD"
  JWT_SECRET: "REDACTED_JWT_SECRET"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "quoter-group"
