apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: quoter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path   # k3s default
  resources:
    requests:
      storage: 2Gi
